# Generated by Django 3.2.3 on 2021-05-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airways', '0002_auto_20210519_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='base_price',
            field=models.FloatField(default=10, verbose_name='Base ticket price'),
            preserve_default=False,
        ),
    ]
